-- CreateTable
CREATE TABLE `Worker` (
    `WORKER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` CHAR(25) NULL,
    `LAST_NAME` CHAR(25) NULL,
    `SALARY` INTEGER NULL,
    `JOINING_DATE` DATETIME(0) NULL,
    `DEPARTMENT` CHAR(25) NULL,

    PRIMARY KEY (`WORKER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Bonus` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `WORKER_REF_ID` INTEGER NOT NULL,
    `BONUS_AMOUNT` INTEGER NULL,
    `BONUS_DATE` DATETIME(0) NULL,

    UNIQUE INDEX `Bonus_WORKER_REF_ID_key`(`WORKER_REF_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Title` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `WORKER_REF_ID` INTEGER NOT NULL,
    `WORKER_TITLE` CHAR(25) NULL,
    `AFFECTED_FROM` DATETIME(0) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NULL,
    `email` VARCHAR(100) NOT NULL,

    UNIQUE INDEX `Users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Bonus` ADD CONSTRAINT `Bonus_WORKER_REF_ID_fkey` FOREIGN KEY (`WORKER_REF_ID`) REFERENCES `Worker`(`WORKER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Title` ADD CONSTRAINT `Title_WORKER_REF_ID_fkey` FOREIGN KEY (`WORKER_REF_ID`) REFERENCES `Worker`(`WORKER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
