-- DropForeignKey
ALTER TABLE `bonus` DROP FOREIGN KEY `Bonus_WORKER_REF_ID_fkey`;

-- DropIndex
DROP INDEX `Bonus_WORKER_REF_ID_key` ON `bonus`;

-- AddForeignKey
ALTER TABLE `Bonus` ADD CONSTRAINT `Bonus_WORKER_REF_ID_fkey` FOREIGN KEY (`WORKER_REF_ID`) REFERENCES `Worker`(`WORKER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
